logging:
  level: INFO
  loggers:
    nl.knaw.huc: DEBUG
    nl.knaw.huc.resources: TRACE

server:
  applicationConnectors:
    - type: http #Note! if you change this you might or might not also want to change the baseUri
      port: ${SERVER_PORT:- 8080} #Note! if you change this you might or might not also want to change the baseUri
  adminConnectors:
    - type: http
      port: ${ADMIN_PORT:- 8081}

elasticsearchClient:
  hostName: ${ELASTICSEARCH_HOST:- localhost}
  port: ${ELASTICSEARCH_PORT:- 9200}
  scheme: ${ELASTICSEARCH_SCHEME:- http}
