# Use from the root of the project: docker-compose -f docker/docker-compose-local.yml up -d
version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - nginxproxynetwork
  redis:
    image: redis:5-alpine
    networks:
      - nginxproxynetwork
  resussun:
    image: knawhuc/resussun:latest
    environment:
      ELASTICSEARCH_HOST: "elasticsearch"
    ports:
      - "8080:80"
      - "8081:81"
    networks:
      - nginxproxynetwork
    volumes:
      - ../target/appassembler/bin:/app/bin
      - ../target/appassembler/repo:/app/repo
      - ../config.yml:/app/config.yml
networks:
  nginxproxynetwork:
