version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - nginxproxynetwork
  resussun:
    image: knawhuc/resussun:latest
    environment:
      ELASTICSEARCH_HOST: "elasticsearch"
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - nginxproxynetwork
networks:
  nginxproxynetwork:
