version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - nginxproxynetwork
  redis:
    image: redis:5-alpine
    networks:
      - nginxproxynetwork
  resussun:
    image: knawhuc/resussun:latest
    environment:
      ELASTICSEARCH_HOST: "elasticsearch"
      REDIS_HOST: "redis"
    ports:
      - "8080:80"
      - "8081:81"
    networks:
      - nginxproxynetwork
networks:
  nginxproxynetwork:
